# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

service: tasks-service 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  environment: 
    RDS_HOST: ${file(../todo_app_backend_config/serverless_env.json):RDS_HOST}
    RDS_USER: ${file(../todo_app_backend_config/serverless_env.json):RDS_USER}
    RDS_PASSWORD: ${file(../todo_app_backend_config/serverless_env.json):RDS_PASSWORD}
    RDS_DATABASE: ${file(../todo_app_backend_config/serverless_env.json):RDS_DATABASE}

functions:
  tasks:
    handler: tasks.handler
    events:
      - http:
          path: tasks
          method: get
          cors: true
      - http:
          path: tasks/userid/{userId}
          method: get
          cors: true
      - http:
          path: tasks/{taskId}
          method: get
          cors: true
      - http:
          path: tasks
          method: post
          cors: true
      - http:
          path: tasks
          method: put
          cors: true 
      - http:
          path: tasks/{taskId}
          method: DELETE
          cors: true 
     
          